title: Noah Prowell # your name (or website title) here
logo: "images/profile_photo.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science • Analytics • Strategy | Driving Business Impact with Data
  <br>
  Reach out on Linkedin!
  
theme: jekyll-theme-cayman
google_analytics: G-XQ95T2NBZ4 # your Google Analytics tracking ID here
