title: Noah Prowell # your name (or website title) here
logo: "images/profile_photo.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist
  <br>
  Data Analyst
  <br>
  Feel free to reach out on Linkedin! 
  <br><br>
  <a href="https://www.linkedin.com/in/noah-prowell/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-slate
google_analytics: G-XQ95T2NBZ4 # your Google Analytics tracking ID here
